#!/bin/bash

# Quick Setup Script for Transaction Logging
# This creates the transaction_logs table in your Supabase database

echo "================================================"
echo "   Transaction Logging Setup"
echo "================================================"
echo ""
echo "⚠️  IMPORTANT: You must run the SQL migration manually"
echo ""
echo "Steps to set up:"
echo ""
echo "1. Open your Supabase Dashboard"
echo "   → https://supabase.com/dashboard"
echo ""
echo "2. Go to SQL Editor (left sidebar)"
echo ""
echo "3. Click 'New Query'"
echo ""
echo "4. Copy the entire contents of:"
echo "   📁 database/create_transaction_logs.sql"
echo ""
echo "5. Paste into the SQL Editor"
echo ""
echo "6. Click 'Run' (or press Ctrl+Enter)"
echo ""
echo "7. Restart your backend server:"
echo "   cd backend"
echo "   npm start"
echo ""
echo "================================================"
echo ""
echo "Why is this needed?"
echo "- Logs all payment transactions"
echo "- Generates PDF receipts automatically"
echo "- Required for receipt download feature"
echo ""
echo "After setup, receipts will be available at:"
echo "- Profile → Backed Projects → Download Receipt"
echo "- Welcome popup after backing a project"
echo ""
echo "================================================"
