#!/bin/bash

# Test Database Connection and Verify Setup
# This script helps verify the transaction_logs table was created correctly

echo "================================================"
echo "   Transaction Logs - Setup Verification"
echo "================================================"
echo ""

# Check if SQL file exists
if [ ! -f "create_transaction_logs.sql" ]; then
    echo "❌ Error: create_transaction_logs.sql not found"
    echo "   Make sure you're in the database/ directory"
    exit 1
fi

echo "✅ SQL file found: create_transaction_logs.sql"
echo ""
echo "📝 File has been updated to handle existing objects"
echo "   - Uses 'DROP TRIGGER IF EXISTS'"
echo "   - Uses 'DROP POLICY IF EXISTS'"
echo "   - Safe to run multiple times"
echo ""
echo "================================================"
echo "   Next Steps:"
echo "================================================"
echo ""
echo "1. Copy the ENTIRE contents of create_transaction_logs.sql"
echo ""
echo "2. Go to Supabase Dashboard → SQL Editor"
echo ""
echo "3. Paste and click 'Run'"
echo ""
echo "4. You should see: ✓ Success (no errors)"
echo ""
echo "5. Verify the table exists:"
echo "   - Go to Table Editor"
echo "   - Find 'transaction_logs' table"
echo "   - Should have ~20 columns"
echo ""
echo "6. Restart backend server:"
echo "   cd ../backend"
echo "   npm start"
echo ""
echo "7. Test by making a payment"
echo ""
echo "================================================"
echo ""
echo "If you still see errors, the most common issues are:"
echo ""
echo "1. Permission Issues"
echo "   → Make sure you're using the correct Supabase project"
echo "   → Use the SQL Editor (not direct psql)"
echo ""
echo "2. Partial Creation"
echo "   → The updated SQL file now handles this"
echo "   → Just run it again"
echo ""
echo "3. Foreign Key Issues"
echo "   → Make sure these tables exist first:"
echo "      - main_projects"
echo "      - users"
echo "      - reward_table"
echo "      - pledges"
echo ""
echo "================================================"
echo ""
echo "After successful setup:"
echo "✅ Transaction logging will work"
echo "✅ PDF receipts will be generated"
echo "✅ Download buttons will appear"
echo ""
